name: DingTalk Notify
on:
  push:
    branches:
      - master
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          yarn
      - name: Build
        run: |
          yarn build

      - uses: ./
        with:
          token: ${{ secrets.DINGTALK_TOKEN }}
          secret: ${{ secrets.DINGTALK_SECRET }} # only for signed bot
          msgtype: text
          content: |
          {
            "content": "Hello DingTalk"
          }
