name: DingTalk Notify On PR Created
on:
  pull_request_target:
    types: [opened]
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Install
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - uses: ./
        with:
          token: ${{ secrets.DINGTALK_TOKEN }}
          secret: ${{ secrets.DINGTALK_SECRET }}
          msgtype: markdown
          content: |
            {
              "title": "[${{ github.event.pull_request.user.login }}](${{ github.event.pull_request.user.html_url }}) CREATED PullRequest: ${{ github.event.pull_request.title }} ([#${{ github.event.pull_request.number }}](github.event.pull_request.html_url))",
              "text": ${{ toJSON(github.event.pull_request.body) }}
            }
